export const api ={
    home_nft:[
        {
            img:"https://res.cloudinary.com/hamskid/image/upload/v1668255748/Frame_151_30_ghuomd.png",
            name:"Desert King",
            mbt:1,
            distance:25,
            stay_day:2,
        },
        {
            img:"https://res.cloudinary.com/hamskid/image/upload/v1668255747/Frame_151_jd10rv.png",
            name:"Desert King",
            mbt:1,
            distance:25,
            stay_day:2,
        },
        {
            img:"https://res.cloudinary.com/hamskid/image/upload/v1668255744/Frame_151_29_ysnhmc.png",
            name:"Desert King",
            mbt:1,
            distance:25,
            stay_day:2,
        },
        {
            img:"https://res.cloudinary.com/hamskid/image/upload/v1668255743/Frame_151_11_nlsggr.png",
            name:"Desert King",
            mbt:1,
            distance:25,
            stay_day:2,
        },
        {
            img:"https://res.cloudinary.com/hamskid/image/upload/v1668255743/Frame_151_10_tq0tq7.png",
            name:"Desert King",
            mbt:1,
            distance:25,
            stay_day:2,
        },
        {
            img:"https://res.cloudinary.com/hamskid/image/upload/v1668255743/Frame_151_28_itk85y.png",
            name:"Desert King",
            mbt:1,
            distance:25,
            stay_day:2,
        },
        {
            img:"https://res.cloudinary.com/hamskid/image/upload/v1668255742/Frame_151_7_uimaod.png",
            name:"Desert King",
            mbt:1,
            distance:25,
            stay_day:2,
        },
        {
            img:"https://res.cloudinary.com/hamskid/image/upload/v1668255742/Frame_151_27_pztmyo.png",
            name:"Desert King",
            mbt:1,
            distance:25,
            stay_day:2,
        }
    ],
    nft_collections:[
        {
            img:"https://res.cloudinary.com/hamskid/image/upload/v1668255748/Frame_151_30_ghuomd.png",
            name:"Desert King",
            mbt:1,
            distance:25,
            stay_day:2,
        },
        {
            img:"https://res.cloudinary.com/hamskid/image/upload/v1668255747/Frame_151_jd10rv.png",
            name:"Desert King",
            mbt:1,
            distance:25,
            stay_day:2,
        },
        {
            img:"https://res.cloudinary.com/hamskid/image/upload/v1668255744/Frame_151_29_ysnhmc.png",
            name:"Desert King",
            mbt:1,
            distance:25,
            stay_day:2,
        },
        {
            img:"https://res.cloudinary.com/hamskid/image/upload/v1668255743/Frame_151_11_nlsggr.png",
            name:"Desert King",
            mbt:1,
            distance:25,
            stay_day:2,
        },
        {
            img:"https://res.cloudinary.com/hamskid/image/upload/v1668255743/Frame_151_10_tq0tq7.png",
            name:"Desert King",
            mbt:1,
            distance:25,
            stay_day:2,
        },
        {
            img:"https://res.cloudinary.com/hamskid/image/upload/v1668255743/Frame_151_28_itk85y.png",
            name:"Desert King",
            mbt:1,
            distance:25,
            stay_day:2,
        },
        {
            img:"https://res.cloudinary.com/hamskid/image/upload/v1668255742/Frame_151_7_uimaod.png",
            name:"Desert King",
            mbt:1,
            distance:25,
            stay_day:2,
        },
        {
            img:"https://res.cloudinary.com/hamskid/image/upload/v1668255742/Frame_151_27_pztmyo.png",
            name:"Desert King",
            mbt:1,
            distance:25,
            stay_day:2,
        },
        {
            img:"https://res.cloudinary.com/hamskid/image/upload/v1668255742/Frame_151_26_hyvjeq.png",
            name:"Desert King",
            mbt:1,
            distance:25,
            stay_day:2,
        },
        {
            img:"https://res.cloudinary.com/hamskid/image/upload/v1668255742/Frame_151_3_uehdkb.png",
            name:"Desert King",
            mbt:1,
            distance:25,
            stay_day:2,
        },
        {
            img:"https://res.cloudinary.com/hamskid/image/upload/v1668255741/Frame_151_1_on4diq.png",
            name:"Desert King",
            mbt:1,
            distance:25,
            stay_day:2,
        },
        {
            img:"https://res.cloudinary.com/hamskid/image/upload/v1668255741/Frame_151_2_u3wz3o.png",
            name:"Desert King",
            mbt:1,
            distance:25,
            stay_day:2,
        },
        {
            img:"https://res.cloudinary.com/hamskid/image/upload/v1668255741/Frame_151_6_w827sz.png",
            name:"Desert King",
            mbt:1,
            distance:25,
            stay_day:2,
        },
        {
            img:"https://res.cloudinary.com/hamskid/image/upload/v1668255741/Frame_151_4_a5peg5.png",
            name:"Desert King",
            mbt:1,
            distance:25,
            stay_day:2,
        },
        {
            img:"https://res.cloudinary.com/hamskid/image/upload/v1668255748/Frame_151_30_ghuomd.png",
            name:"Desert King",
            mbt:1,
            distance:25,
            stay_day:2,
        },
        {
            img:"https://res.cloudinary.com/hamskid/image/upload/v1668255744/Frame_151_29_ysnhmc.png",
            name:"Desert King",
            mbt:1,
            distance:25,
            stay_day:2,
        }
        
    ]
}